"""
Django settings for cove project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import warnings
import environ
import raven
from django.utils.crypto import get_random_string
from django.utils.translation import ugettext_lazy as _

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

chars = 'abcdefghijklmnopqrstuvwxyz0123456789!@#%^&*(-_=+)'
secret_key = get_random_string(50, chars)
if 'SECRET_KEY' not in os.environ:
    warnings.warn('SECRET_KEY should be added to Environment Variables. Random key will be used instead.')

env = environ.Env(  # set default values and casting
    SENTRY_DSN=(str, ''),
    DEBUG=(bool, True),
    PIWIK_URL=(str, ''),
    PIWIK_SITE_ID=(str, ''),
    PIWIK_DIMENSION_MAP=(dict, {}),
    GOOGLE_ANALYTICS_ID=(str, ''),
    PREFIX_MAP=(dict, {}),
    ALLOWED_HOSTS=(list, []),
    SECRET_KEY=(str, secret_key),
    DB_NAME=(str, os.path.join(BASE_DIR, 'db.sqlite3')),
    DEBUG_TOOLBAR=(bool, False),
    SCHEMA_URL_OCDS=(str, 'http://standard.open-contracting.org/schema/{}/'),
    SCHEMA_URL_360=(str, 'https://raw.githubusercontent.com/ThreeSixtyGiving/standard/master/schema/'),
)

PIWIK = {
    'url': env('PIWIK_URL'),
    'site_id': env('PIWIK_SITE_ID'),
    'dimension_map': env('PIWIK_DIMENSION_MAP'),
}

GOOGLE_ANALYTICS_ID = env('GOOGLE_ANALYTICS_ID')


MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

DEALER_TYPE = 'git'

PREFIX_MAP = env('PREFIX_MAP')


COVE_CONFIG_BY_NAMESPACE = {
    'base_template_name': {
        'cove-ocds': 'base_ocds.html',
        'cove-360': 'base_360.html',
        'cove-resourceprojects': 'base_resourceprojects.html',
        'default': 'base_generic.html',
    },
    'application_name': {
        'cove-ocds': _('Open Contracting Data Standard Validator'),
        'cove-360': _('360Giving Data Quality Tool'),
        'default': _('CoVE'),
    },
    'application_strapline': {
        'cove-ocds': _('Validate and Explore your data.'),
        'cove-360': _('Convert, Validate, Explore 360Giving Data'),
        'default': _('Convert, Validate, Explore'),
    },
    'schema_url': {
        'cove-360': env('SCHEMA_URL_360'),
        'cove-ocds': env('SCHEMA_URL_OCDS'),
        'default': None
    },
    'schema_name': {
        'cove-360': '360-giving-package-schema.json',
        'cove-ocds': {'release': 'release-package-schema.json',
                      'record': 'record-package-schema.json'},
        'default': None
    },
    'schema_version': {  # Default schema version
        'cove-ocds': '1.0.2',
        'cove-360': None,
        'default': None
    },
    'schema_version_choices': {
        'cove-ocds': ('1.0.2', '1.0.1', '1.0.0'),  # Keep descending order when adding new versions
        'cove-360': None,
        'default': None
    },
    'item_schema_name': {  # Schema url for an individual item e.g. a single release or grant
        'cove-ocds': 'release-schema.json',
        'cove-360': '360-giving-schema.json',
        'default': None
    },
    'root_list_path': {
        'cove-ocds': 'releases',
        'cove-360': 'grants',
        'default': None
    },
    'root_id': {
        'cove-ocds': 'ocid',
        'default': ''
    },
    'convert_titles': {
        'cove-360': True,
        'default': False
    },
    'input_methods': {
        'default': ['upload', 'url', 'text'],
        'cove-resourceprojects': ['upload', 'url']
    },
    'support_email': {
        'cove-ocds': 'data@open-contracting.org',
        'cove-360': 'support@threesixtygiving.org',
        'default': 'code@opendataservices.coop',
    },
}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env('ALLOWED_HOSTS')

if env('SENTRY_DSN'):
    RAVEN_CONFIG = {
        'dsn': env('SENTRY_DSN'),
        'release': raven.fetch_git_sha(os.path.join(os.path.dirname(__file__), '..')),
    }


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.humanize',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bootstrap3',
    'cove',
    'cove.input',
    'cove.dataload',
    'raven.contrib.django.raven_compat',
)

if env('DEBUG_TOOLBAR'):
    INSTALLED_APPS += ('debug_toolbar',)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'dealer.contrib.django.Middleware',
    'cove.middleware.CoveConfigByNamespaceMiddleware',
)

ROOT_URLCONF = 'cove.urls_multi'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cove.context_processors.analytics',
                'cove.context_processors.cove_namespace_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'cove.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': env('DB_NAME'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')


LANGUAGES = (
    ('en', 'English'),
    ('es', 'Spanish'),
)
LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)


# Logging

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s '
                      '%(process)d %(thread)d %(message)s'
        },
    },
    'handlers': {
        'sentry': {
            'level': 'ERROR',
            'class': 'raven.contrib.django.raven_compat.handlers.SentryHandler',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose'
        }
    },
    'loggers': {
        'django.db.backends': {
            'level': 'ERROR',
            'handlers': ['console'],
            'propagate': False,
        },
        'raven': {
            'level': 'DEBUG',
            'handlers': ['console'],
            'propagate': False,
        },
        'sentry.errors': {
            'level': 'DEBUG',
            'handlers': ['console'],
            'propagate': False,
        },
        '': {
            'level': 'WARNING',
            'handlers': ['console', 'sentry'],
        },
    },
}
